import React, { useEffect, useState } from "react";
import { Activity, Download } from "lucide-react";
import { Card } from "../core/Card";
import { analysisAPI } from "../../api/analysisAPI";

export function PcapViewer({ fileUrl, parsed }) {
  const [packetCount, setPacketCount] = useState(parsed?.summary?.totalPackets || 0);
  const [latestFile, setLatestFile] = useState(null);

  // Fetch actual packet count on mount
  useEffect(() => {
    async function fetchAnalysis() {
      try {
        const data = await analysisAPI.getLatestCaptureAnalysis();
        setPacketCount(data.packetCount);
        setLatestFile(data.file);
      } catch (err) {
        console.error("[!] Failed to fetch analysis:", err.message);
      }
    }
    fetchAnalysis();
  }, []);

  if (!parsed) return null;

  const fileName = latestFile || (fileUrl ? fileUrl.split(/[/\\]/).pop() : "Unknown File");

  return (
    <Card title="Capture Analysis" icon={Activity}>
      <div className="space-y-4">
        <div className="bg-black/30 rounded p-3">
          <div className="text-sm text-cyan-400 mb-1 leading-relaxed">
            Performing in-depth network analysis on the captured data file{" "}
            <span className="text-white font-semibold">{fileName}</span> to
            reveal traffic patterns and communication flows.
          </div>
          <div className="text-xs text-gray-400 mb-2">
            Generated by Shadow-Scan Network Analyzer
          </div>
          <div className="text-sm text-cyan-400">
            Total Packets:{" "}
            <span className="text-white font-bold">{packetCount}</span>
          </div>
        </div>

        {/* Rest of your code (protocols, flows, etc.) stays the same */}
      </div>
    </Card>
  );
}
